# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mote_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(437, 295)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.general = QtWidgets.QRadioButton(self.widget)
        self.general.setObjectName("general")
        self.verticalLayout.addWidget(self.general)
        self.parents = QtWidgets.QRadioButton(self.widget)
        self.parents.setObjectName("parents")
        self.verticalLayout.addWidget(self.parents)
        self.energy = QtWidgets.QRadioButton(self.widget)
        self.energy.setObjectName("energy")
        self.verticalLayout.addWidget(self.energy)
        self.horizontalLayout.addWidget(self.widget)
        self.information = QtWidgets.QListView(self.widget_2)
        self.information.setObjectName("information")
        self.horizontalLayout.addWidget(self.information)
        self.verticalLayout_2.addWidget(self.widget_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Mote Information"))
        self.general.setText(_translate("Dialog", "General Info"))
        self.parents.setText(_translate("Dialog", "Selected Parents"))
        self.energy.setText(_translate("Dialog", "Energy Trace"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
